#
# ~/.bashrc

# Ignore commands starting with a space and duplicates of specific commands
export HISTIGNORE="ls:cd:ll:ls -la:history:"

# Ignore duplicates and space of commands when writing history
export HISTCONTROL=ignoreboth

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -f ~/.bash_prompt ];then
    . ~/.bash_prompt
fi

if [ -f ~/.bash_aliases ];then
    . ~/.bash_aliases
fi
